export const GET_ALL_GAMES = 'GET_ALL_GAMES'
export const CLEAR_GAMES = 'CLEAR_GAMES'
export const SORT_GAMES = 'SORT_GAMES'
export const GET_GENRES = 'GET_GENRES'
export const FILTER_GAMES = 'FILTER_GAMES'
